{{- $values := .Values -}}
{{- $storageClassName := include "mysql.fullname" . -}}
{{ range $i, $e := until (int .Values.replicaCount) }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-data-{{ lower (randAlphaNum 8) }}
  labels:
    app: mysql-data
spec:
  storageClassName: {{ $storageClassName }}
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: {{ $values.persistentvolume.storage }}
  local:
    path: {{ trimSuffix "/" $values.persistentvolume.node_path }}/data-{{ $i }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: role
          operator: In
          values:
          - db
{{ end }}
