{{- if .Values.init_db.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql.fullname" . }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
stringData:
  MYSQL_USER: {{ .Values.init_db.user | default "wpadmin" | quote }}
  MYSQL_PASSWORD: {{ required "Please specify user password: --set init_db.pass" .Values.init_db.pass | quote }}
  MYSQL_DATABASE: {{ .Values.init_db.name | default "wordpress" | quote }}
{{- end }}
